#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jun 30 14:36:16 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a90b1118a59a42fcb81e1318a4cd7222 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot UART_RX_TB_behav xil_defaultlib.UART_RX_TB xil_defaultlib.glbl -log elaborate.log"
xelab -wto a90b1118a59a42fcb81e1318a4cd7222 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot UART_RX_TB_behav xil_defaultlib.UART_RX_TB xil_defaultlib.glbl -log elaborate.log

